In [2]:
import numpy as np

1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.


In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5])
# for i in arr:
#   print(i)
print(arr.dtype)


int64


2. Given a NumPy array 'arr', check if its data type is float64.


In [ ]:
arr = np.array([1.5, 2.6, 3.7])
#arr = np.array([1.5, 2.6, 3.7,"str"])

if arr.dtype == np.float64:
    print("The data type of the array is float64.")
else:
    print("The data type of the array is not float64.")


The data type of the array is float64.


3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.


In [ ]:
arr = np.array([1 + 2j, 3 + 4j, 5 + 6j])

print(arr.dtype)


complex128


4. Convert an existing NumPy array 'arr' of integers to float32 data type.


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr_float32 = arr.astype(np.float32)

print(arr_float32.dtype)

float32


5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.


In [ ]:
arr = np.array([1.5, 2.6, 3.7], dtype=np.float64)

arr_float32 = arr.astype(np.float32)

print(arr_float32.dtype)

float32


6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.


In [ ]:
def array_attributes(arr):
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype
    return shape, size, dtype


arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, size, dtype = array_attributes(arr)
print("Shape:", shape)
print("Size:", size)
print("Data Type:", dtype)


Shape: (2, 3)
Size: 6
Data Type: int64


7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.


In [ ]:
def array_dimension(arr):
      return arr.ndim


arr1 = np.array([1, 2, 3])
arr2 = np.array([[1, 2], [3, 4]])
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("Dimensionality of arr1:", array_dimension(arr1))
print("Dimensionality of arr2:", array_dimension(arr2))
print("Dimensionality of arr3:", array_dimension(arr3))


Dimensionality of arr1: 1
Dimensionality of arr2: 2
Dimensionality of arr3: 3


8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.


In [ ]:
def item_size_info(arr):

    item_size = arr.itemsize
    total_size = arr.size * item_size
    return item_size, total_size


arr = np.array([[1, 2, 3], [4, 5, 6]])
item_size, total_size = item_size_info(arr)
print("Item size:", item_size, "bytes")
print("Total size:", total_size, "bytes")


Item size: 8 bytes
Total size: 48 bytes


9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.


In [ ]:
def array_strides(arr):

    return arr.strides

arr = np.array([[1, 2, 3], [4, 5, 6]])
strides = array_strides(arr)
print("Strides:", strides)


Strides: (24, 8)


10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.


In [ ]:

def shape_stride_relationship(arr):
    shape = arr.shape
    strides = arr.strides
    return shape, strides

arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, strides = shape_stride_relationship(arr)
print("Shape:", shape)
print("Strides:", strides)


Shape: (2, 3)
Strides: (24, 8)


11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.


In [ ]:

def create_zeros_array(n):
    return np.zeros(n)

n = 5
zeros_array = create_zeros_array(n)
print(zeros_array)


[0. 0. 0. 0. 0.]


12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.


In [ ]:

def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

rows = 3
cols = 4
ones_matrix = create_ones_matrix(rows, cols)
print(ones_matrix)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step'.


In [ ]:
import numpy as np

def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

start = 1
stop = 10
step = 2
range_array = generate_range_array(start, stop, step)
print(range_array)


[1 3 5 7 9]


14. Design a function `generate_linear_space` that takes two floats start`, `stop`, and an integer `num`as arguments and generates a NumPy array with num equally spaced values between 'start` and `stop` (inclusive).


In [ ]:
import numpy as np

def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

start = 0.5
stop = 2.5
num = 5
linear_space_array = generate_linear_space(start, stop, num)
print(linear_space_array)


[0.5 1.  1.5 2.  2.5]


15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.


In [ ]:
import numpy as np

def create_identity_matrix(n):
    return np.eye(n)

n = 3
identity_matrix = create_identity_matrix(n)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


16. Write a function that takes a Python list and converts it into a NumPy array.


In [ ]:
import numpy as np

def list_to_numpy_array(lst):
    return np.array(lst)

my_list = [1, 2, 3, 4, 5]
numpy_array = list_to_numpy_array(my_list)
print(numpy_array)


[1 2 3 4 5]


17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.

In [ ]:
original_array = np.array([[1, 2, 3], [4, 5, 6]])
view_array = original_array.view()
view_array[0, 0] = 100

print("Original array:")
print(original_array)
print("\nView array:")
print(view_array)


Original array:
[[100   2   3]
 [  4   5   6]]

View array:
[[100   2   3]
 [  4   5   6]]


18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.


In [ ]:
def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
concatenated_array_rows = concatenate_arrays(array1, array2, axis=0)
print("Concatenated array along rows (axis=0):")
print(concatenated_array_rows)
concatenated_array_columns = concatenate_arrays(array1, array2, axis=1)
print("\nConcatenated array along columns (axis=1):")
print(concatenated_array_columns)


Concatenated array along rows (axis=0):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Concatenated array along columns (axis=1):
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy. concatenate`.


In [ ]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7], [8]])

concatenated_array = np.concatenate((array1, array2), axis=1)

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nConcatenated array:")
print(concatenated_array)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[7]
 [8]]

Concatenated array:
[[1 2 3 7]
 [4 5 6 8]]


20. Write a function that vertically stacks multiple NumPy arrays given as a list.


In [ ]:
def vertical_stack_arrays(arrays):
    return np.vstack(arrays)

array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9]])
stacked_array = vertical_stack_arrays([array1, array2])
print("Stacked array:")
print(stacked_array)


Stacked array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.


In [ ]:
def create_integer_array(start, stop, step=1):
    return np.arange(start, stop + 1, step, dtype=int)

start = 1
stop = 10
step = 2
integer_array = create_integer_array(start, stop, step)
print("Integer array:")
print(integer_array)


Integer array:
[1 3 5 7 9]


22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).


In [ ]:
def generate_equally_spaced_array():
    return np.linspace(0, 1, 10)

equally_spaced_array = generate_equally_spaced_array()
print("Equally spaced array:")
print(equally_spaced_array)


Equally spaced array:
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).


In [ ]:
import numpy as np

def generate_logarithmically_spaced_array():
    return np.logspace(start=np.log10(1), stop=np.log10(1000), num=5)

logarithmically_spaced_array = generate_logarithmically_spaced_array()
print("Logarithmically spaced array:")
print(logarithmically_spaced_array)


Logarithmically spaced array:
[   1.            5.62341325   31.6227766   177.827941   1000.        ]


24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.


In [ ]:
import numpy as np
import pandas as pd

random_array = np.random.randint(low=1, high=101, size=(5, 3))

df = pd.DataFrame(random_array, columns=['Column1', 'Column2', 'Column3'])

print("Pandas DataFrame:")
print(df)


Pandas DataFrame:
   Column1  Column2  Column3
0       45       44       58
1       71       15       48
2       50       85       21
3        1       56       59
4       80       43       36


25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.


In [ ]:
def replace_negative_values_with_zeros(df, column_name):
    df[column_name] = df[column_name].apply(lambda x: max(0, x))
    return df

data = {'A': [1, -2, 3, -4, 5],
        'B': [10, -20, 30, -40, 50]}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

column_name = 'A'
df_updated = replace_negative_values_with_zeros(df, column_name)

print("\nDataFrame with negative values replaced by zeros in column '{}'".format(column_name))
print(df_updated)


Original DataFrame:
   A   B
0  1  10
1 -2 -20
2  3  30
3 -4 -40
4  5  50

DataFrame with negative values replaced by zeros in column 'A'
   A   B
0  1  10
1  0 -20
2  3  30
3  0 -40
4  5  50


26. Access the 3rd element from the given NumPy array.


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
third_element = arr[2]

print("The 3rd element from the given NumPy array is:", third_element)


The 3rd element from the given NumPy array is: 30


27. Retrieve the element at index (1, 2) from the 2D NumPy array.


In [ ]:

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

element_at_index_1_2 = arr_2d[1, 2]

print("The element at index (1, 2) from the given 2D NumPy array is:", element_at_index_1_2)


The element at index (1, 2) from the given 2D NumPy array is: 6


28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.


In [ ]:

arr = np.array([3, 8, 2, 10, 5, 7])
greater_than_5 = arr[arr > 5]

print("Elements greater than 5 from the given NumPy array:")
print(greater_than_5)


Elements greater than 5 from the given NumPy array:
[ 8 10  7]


29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

sliced_arr = arr[2:6]

print("Elements from index 2 to 5 (inclusive) from the given NumPy array:")
print(sliced_arr)


Elements from index 2 to 5 (inclusive) from the given NumPy array:
[3 4 5 6]


30. Slice the 2D NumPy array to extract the sub-array`[[2, 3], [5, 6]]` from the given array.

In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])


sub_array = arr_2d[0:2, 1:3]

print("Sub-array [[2, 3], [5, 6]] from the given 2D NumPy array:")
print(sub_array)


Sub-array [[2, 3], [5, 6]] from the given 2D NumPy array:
[[2 3]
 [5 6]]


31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.


In [ ]:
def extract_elements_by_indices(arr_2d, indices):
    return arr_2d.flatten()[indices]

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

indices = np.array([4, 0, 5, 2, 1])

extracted_elements = extract_elements_by_indices(arr_2d, indices)
print("Extracted elements based on the provided indices:")
print(extracted_elements)


Extracted elements based on the provided indices:
[5 1 6 3 2]


32. Create a NumPy function that filters elements greater than a threshold from a given ID array using boolean indexing.


In [ ]:
def filter_elements_by_threshold(id_array, threshold):
    return id_array[id_array > threshold]


id_array = np.array([10, 20, 30, 40, 50])
threshold = 25

filtered_elements = filter_elements_by_threshold(id_array, threshold)
print("Filtered elements greater than", threshold, "from the given ID array:")
print(filtered_elements)


Filtered elements greater than 25 from the given ID array:
[30 40 50]


33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.


In [ ]:
def extract_elements_from_3d_array(arr_3d, indices_dim1, indices_dim2, indices_dim3):
    return arr_3d[indices_dim1, indices_dim2, indices_dim3]

arr_3d = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],

                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]],

                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])

indices_dim1 = np.array([0, 1, 2])
indices_dim2 = np.array([1, 0, 2])
indices_dim3 = np.array([2, 1, 0])

extracted_elements = extract_elements_from_3d_array(arr_3d, indices_dim1, indices_dim2, indices_dim3)
print("Extracted elements from the 3D array based on the provided indices:")
print(extracted_elements)


Extracted elements from the 3D array based on the provided indices:
[ 6 11 25]


34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.


In [ ]:

def filter_elements_with_conditions(arr, condition1, condition2):

    return arr[(condition1) & (condition2)]

arr = np.array([1, 2, 3, 4, 5])
condition1 = arr > 2
condition2 = arr % 2 == 0


filtered_elements = filter_elements_with_conditions(arr, condition1, condition2)
print("Elements from the array where both conditions are satisfied:")
print(filtered_elements)


Elements from the array where both conditions are satisfied:
[4]


35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.


In [ ]:
import numpy as np

def extract_elements_from_2d_array(arr_2d, row_indices, col_indices):
    return arr_2d[row_indices, col_indices]


arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 0, 2])

extracted_elements = extract_elements_from_2d_array(arr_2d, row_indices, col_indices)
print("Extracted elements from the 2D array based on the provided row and column indices:")
print(extracted_elements)


Extracted elements from the 2D array based on the provided row and column indices:
[2 4 9]


36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.


In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

result = arr + 5

print("Original array:")
print(arr)

print("\nArray after adding a scalar value of 5 to each element:")
print(result)


Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array after adding a scalar value of 5 to each element:
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


37. Consider two arrays arrl of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arrl using NumPy broadcasting.


In [ ]:

arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

arr1_reshaped = arr1.reshape(3, 1)

result = arr1_reshaped * arr2

print("Array arr1:")
print(arr1)

print("\nArray arr2:")
print(arr2)

print("\nResult after multiplying each row of arr2 by the corresponding element in arr1:")
print(result)


Array arr1:
[[1 2 3]]

Array arr2:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Result after multiplying each row of arr2 by the corresponding element in arr1:
[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]]


38. Given a ID array arrl of shape (1, 4) and a 2D array arr2 of shape (4,3), add arrl to each row of arr2 using NumPy broadcasting.


In [ ]:

arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9],
                 [10, 11, 12]])

arr1_reshaped = arr1.reshape(4, 1)
result = arr1_reshaped + arr2

print("Array arr1:")
print(arr1)

print("\nArray arr2:")
print(arr2)

print("\nResult after adding arr1 to each row of arr2:")
print(result)


Array arr1:
[[1 2 3 4]]

Array arr2:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Result after adding arr1 to each row of arr2:
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


39. Consider two arrays arrl of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.


In [ ]:

arr1 = np.array([[1],
                  [2],
                  [3]])

arr2 = np.array([[4, 5, 6]])
result = arr1 + arr2

print("Array arr1:")
print(arr1)

print("\nArray arr2:")
print(arr2)

print("\nResult after adding arr1 and arr2 using broadcasting:")
print(result)


Array arr1:
[[1]
 [2]
 [3]]

Array arr2:
[[4 5 6]]

Result after adding arr1 and arr2 using broadcasting:
[[5 6 7]
 [6 7 8]
 [7 8 9]]


40. Given arrays arrl of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.


In [ ]:
arr1 = np.array([[1, 2, 3],
                  [4, 5, 6]])

arr2 = np.array([[7, 8],
                 [9, 10]])

arr2_reshaped = np.expand_dims(arr2, axis=2)


result = arr1 * arr2_reshaped

print("Array arr1:")
print(arr1)

print("\nArray arr2:")
print(arr2)

print("\nResult after multiplication using broadcasting:")
print(result)


Array arr1:
[[1 2 3]
 [4 5 6]]

Array arr2:
[[ 7  8]
 [ 9 10]]

Result after multiplication using broadcasting:
[[[ 7 14 21]
  [32 40 48]]

 [[ 9 18 27]
  [40 50 60]]]


41. Calculate column-wise mean for the given array: arr = np.array([[1, 2, 3], [4, 5, 6]])


In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

column_means = np.mean(arr, axis=0)

print("Given array:")
print(arr)

print("\nColumn-wise mean:")
print(column_means)


Given array:
[[1 2 3]
 [4 5 6]]

Column-wise mean:
[2.5 3.5 4.5]


42. Find maximum value in each row of the given array:


In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])


max_values_per_row = np.max(arr, axis=1)

print("Given array:")
print(arr)

print("\nMaximum value in each row:")
print(max_values_per_row)


Given array:
[[1 2 3]
 [4 5 6]]

Maximum value in each row:
[3 6]


43. For the given array, find indices of maximum value in each column.


In [ ]:

arr = np.array([[1, 2, 3],
                [4, 5, 6]])


max_indices_per_column = np.argmax(arr, axis=0)

print("Given array:")
print(arr)

print("\nIndices of maximum value in each column:")
print(max_indices_per_column)


Given array:
[[1 2 3]
 [4 5 6]]

Indices of maximum value in each column:
[1 1 1]


44. For the given array, apply custom function to calculate moving sum along rows.


In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])


def moving_sum(row):
    return np.convolve(row, np.ones(2), mode='valid')


moving_sum_result = np.apply_along_axis(moving_sum, axis=1, arr=arr)

print("Given array:")
print(arr)

print("\nMoving sum along rows:")
print(moving_sum_result)


Given array:
[[1 2 3]
 [4 5 6]]

Moving sum along rows:
[[ 3.  5.]
 [ 9. 11.]]


45. In the given array, check if all elements in each column are even.


In [ ]:

arr = np.array([[2, 4, 6],
                [2, 5, 7]])

all_even_columns = np.all(arr % 2 == 0, axis=0)

print("Given array:")
print(arr)

print("\nAre all elements in each column even?")
print(all_even_columns)


Given array:
[[2 4 6]
 [2 5 7]]

Are all elements in each column even?
[ True False False]


46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.


In [ ]:

def reshape_matrix(arr, m, n):
    reshaped_matrix = np.reshape(arr, (m, n))
    return reshaped_matrix

arr = np.array([1, 2, 3, 4, 5, 6])
m = 2
n = 3
result = reshape_matrix(arr, m, n)
print("Original array:")
print(arr)
print("\nReshaped matrix:")
print(result)


Original array:
[1 2 3 4 5 6]

Reshaped matrix:
[[1 2 3]
 [4 5 6]]


47. Create a function that takes a matrix as input and returns the flattened array.


In [ ]:
def flatten_matrix(input_matrix):
    flattened_array = input_matrix.flatten()
    return flattened_array

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
result = flatten_matrix(input_matrix)
print("Input matrix:")
print(input_matrix)
print("\nFlattened array:")
print(result)


Input matrix:
[[1 2 3]
 [4 5 6]]

Flattened array:
[1 2 3 4 5 6]


48. Write a function that concatenates two given arrays along a specified axis.


In [ ]:

def concatenate_arrays(array1, array2, axis):
    concatenated_array = np.concatenate((array1, array2), axis=axis)
    return concatenated_array

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
axis = 1

result = concatenate_arrays(array1, array2, axis)
print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nConcatenated array along axis", axis, ":")
print(result)


Array 1:
[[1 2]
 [3 4]]

Array 2:
[[5 6]
 [7 8]]

Concatenated array along axis 1 :
[[1 2 5 6]
 [3 4 7 8]]


49. Create a function that splits an array into multiple sub-arrays along a specified axis.


In [ ]:

def split_array(original_array, axis, indices_or_sections):
    sub_arrays = np.split(original_array, indices_or_sections, axis=axis)
    return sub_arrays

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
axis = 0
indices_or_sections = [1, 2]

result = split_array(original_array, axis, indices_or_sections)
print("Original array:")
print(original_array)
print("\nSub-arrays after splitting along axis", axis, ":")
for sub_array in result:
    print(sub_array)


Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sub-arrays after splitting along axis 0 :
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]


50. Write a function that inserts and then deletes elements from a given array at specified indices.

In [ ]:
import numpy as np

def insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete):
    for index, value in zip(indices_to_insert, values_to_insert):
        original_array = np.insert(original_array, index, value)

    original_array = np.delete(original_array, indices_to_delete)

    return original_array

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

result = insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print("Original array:")
print(original_array)
print("\nArray after insertion and deletion:")
print(result)


Original array:
[1 2 3 4 5]

Array after insertion and deletion:
[ 1 10 11  4  5]


51. Create a NumPy array `arrl` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arrl` and `arr2`.

In [ ]:
import numpy as np


arr1 = np.random.randint(1, 100, size=(1, 10))
print("Random array (arr1):")
print(arr1)


arr2 = np.arange(1, 11)
print("\nArray with integers from 1 to 10 (arr2):")
print(arr2)


result = arr1 + arr2
print("\nElement-wise addition between arr1 and arr2:")
print(result)


Random array (arr1):
[[ 5 41 61  7 85 98  2 68 99 25]]

Array with integers from 1 to 10 (arr2):
[ 1  2  3  4  5  6  7  8  9 10]

Element-wise addition between arr1 and arr2:
[[  6  43  64  11  90 104   9  76 108  35]]


52. Generate a NumPy array `arrl with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arrl` element-wise.


In [3]:
arr1 = np.arange(10, 0, -1)
print("Array arr1 (sequential integers from 10 to 1):")
print(arr1)

arr2 = np.arange(1, 11)
print("\nArray arr2 (integers from 1 to 10):")
print(arr2)

result = arr1 - arr2
print("\nResult of subtracting arr2 from arr1 element-wise:")
print(result)


Array arr1 (sequential integers from 10 to 1):
[10  9  8  7  6  5  4  3  2  1]

Array arr2 (integers from 1 to 10):
[ 1  2  3  4  5  6  7  8  9 10]

Result of subtracting arr2 from arr1 element-wise:
[ 9  7  5  3  1 -1 -3 -5 -7 -9]


53. Create a NumPy array`arrl` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arrl` and `arr2`.


In [6]:
arr1 = np.random.randint(1, 100, size=(5, 5))
print("Random array (arr1):")
print(arr1)

arr2 = np.arange(1, 6)
print("\nArray with integers from 1 to 5 (arr2):")
print(arr2)

result = arr1 * arr2
print("\nElement-wise multiplication between arr1 and arr2:")
print(result)


Random array (arr1):
[[62 47 95  2 51]
 [81 32 58 54 28]
 [57 46 78 77 75]
 [61 77 97 29 17]
 [59 53 58 54 17]]

Array with integers from 1 to 5 (arr2):
[1 2 3 4 5]

Element-wise multiplication between arr1 and arr2:
[[ 62  94 285   8 255]
 [ 81  64 174 216 140]
 [ 57  92 234 308 375]
 [ 61 154 291 116  85]
 [ 59 106 174 216  85]]


54. Generate a NumPy array`arrl` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arrl` by `arr2`.


In [7]:
arr1 = np.arange(2, 12, 2)
print("Array arr1 (even integers from 2 to 10):")
print(arr1)

arr2 = np.arange(1, 6)
print("\nArray arr2 (integers from 1 to 5):")
print(arr2)

result = arr1 / arr2
print("\nElement-wise division between arr1 and arr2:")
print(result)


Array arr1 (even integers from 2 to 10):
[ 2  4  6  8 10]

Array arr2 (integers from 1 to 5):
[1 2 3 4 5]

Element-wise division between arr1 and arr2:
[2. 2. 2. 2. 2.]


55. Create a NumPy array `arrl` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arrl` raised to the power of `arr2` element-wise.


In [8]:
arr1 = np.arange(1, 6)
print("Array arr1 (integers from 1 to 5):")
print(arr1)

arr2 = arr1[::-1]
print("\nArray arr2 (reverse order of arr1):")
print(arr2)

result = np.power(arr1, arr2)
print("\nElement-wise exponentiation of arr1 raised to the power of arr2:")
print(result)


Array arr1 (integers from 1 to 5):
[1 2 3 4 5]

Array arr2 (reverse order of arr1):
[5 4 3 2 1]

Element-wise exponentiation of arr1 raised to the power of arr2:
[ 1 16 27 16  5]


56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.


In [10]:

def count_substring_occurrences(arr, substring):
    count = 0

    for string in arr:
        count += string.count(substring)

    return count
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

substring = 'hello'

occurrences = count_substring_occurrences(arr, substring)
print("Occurrences of '{}' in the array: {}".format(substring, occurrences))


Occurrences of 'hello' in the array: 3


57. Write a function that extracts uppercase characters from a NumPy array of strings.

In [11]:
def extract_uppercase_characters(arr):
    uppercase_chars = []

    for string in arr:
        uppercase_chars.extend([char for char in string if char.isupper()])

    return uppercase_chars

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

uppercase_chars = extract_uppercase_characters(arr)
print("Uppercase characters in the array:", uppercase_chars)


Uppercase characters in the array: ['H', 'W', 'O', 'A', 'I', 'G', 'P', 'T']


58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.


In [13]:
def replace_substring(arr, old_substring, new_substring):
    modified_strings = []

    for string in arr:
        modified_string = string.replace(old_substring, new_substring)
        modified_strings.append(modified_string)

    modified_arr = np.array(modified_strings)

    return modified_arr

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
old_substring = 'apple'
new_substring = 'orange'

modified_arr = replace_substring(arr, old_substring, new_substring)
print("Modified array:")
print(modified_arr)


Modified array:
['orangea' 'banana' 'grape' 'pineorange']


59. Write a function that concatenates strings in a NumPy array element-wise.


In [14]:
def concatenate_strings(arr1, arr2):
    if arr1.shape != arr2.shape:
        raise ValueError("Arrays must have the same shape for element-wise concatenation.")

    concatenated_strings = np.array([string1 + string2 for string1, string2 in zip(arr1, arr2)])

    return concatenated_strings

arr1 = np.array(['Hello', 'World'])
arr2 = np.array([' OpenAI', ' GPT'])

concatenated_arr = concatenate_strings(arr1, arr2)
print("Concatenated array:")
print(concatenated_arr)


Concatenated array:
['Hello OpenAI' 'World GPT']


60. Write a function that finds the length of the longest string in a NumPy array.

In [15]:

def longest_string_length(arr):
    max_length = 0

    for string in arr:
        string_length = len(string)

        if string_length > max_length:
            max_length = string_length

    return max_length

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

max_length = longest_string_length(arr)
print("Length of the longest string:", max_length)


Length of the longest string: 9


61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.


In [17]:
dataset = np.random.randint(1, 1001, size=100)

mean = np.mean(dataset)
median = np.median(dataset)
variance = np.var(dataset)
std_deviation = np.std(dataset)


print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_deviation)


Mean: 517.69
Median: 553.5
Variance: 76154.83389999998
Standard Deviation: 275.9616529519998


62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.


In [18]:
random_numbers = np.random.randint(1, 101, size=50)

percentile_25 = np.percentile(random_numbers, 25)
percentile_75 = np.percentile(random_numbers, 75)

print("25th percentile:", percentile_25)
print("75th percentile:", percentile_75)


25th percentile: 26.0
75th percentile: 70.0


63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's 'corrcoef function.


In [23]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([5, 4, 3, 2, 1])
correlation_coefficient = np.corrcoef(array1, array2)[0, 1]


print("Correlation coefficient between array1 and array2:", correlation_coefficient)


Correlation coefficient between array1 and array2: -0.9999999999999999


64. Create two matrices and perform matrix multiplication using NumPy's 'dot' function.


In [24]:
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])

result_matrix = np.dot(matrix1, matrix2)

print("Result of matrix multiplication:")
print(result_matrix)


Result of matrix multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.


In [25]:
random_numbers = np.random.randint(10, 1001, size=50)


percentiles = np.percentile(random_numbers, [10, 25, 50, 75, 90])


print("10th percentile:", percentiles[0])
print("25th percentile (first quartile):", percentiles[1])
print("50th percentile (median):", percentiles[2])
print("75th percentile (third quartile):", percentiles[3])
print("90th percentile:", percentiles[4])


10th percentile: 68.70000000000002
25th percentile (first quartile): 209.5
50th percentile (median): 471.0
75th percentile (third quartile): 677.75
90th percentile: 774.6000000000001


66. Create a NumPy array of integers and find the index of a specific element.


In [26]:
arr = np.array([1, 2, 3, 4, 5])
element_to_find = 3
index = np.where(arr == element_to_find)[0]
print("Index of element", element_to_find, ":", index)


Index of element 3 : [2]


67. Generate a random NumPy array and sort it in ascending order.


In [29]:
random_array = np.random.randint(1,100,10)

sorted_array = np.sort(random_array)

print("Original array:")
print(random_array)
print("\nSorted array:")
print(sorted_array)


Original array:
[69 58 67 12 29  7 20 90 82 87]

Sorted array:
[ 7 12 20 29 58 67 69 82 87 90]


68. Filter elements >20 in the given NumPy array.


In [30]:
arr = np.array([12, 25, 6, 42, 8, 30])

filtered_array = arr[arr > 20]

print("Filtered array:")
print(filtered_array)


Filtered array:
[25 42 30]


69. Filter elements which are divisible by 3 from a given NumPy array.


In [31]:
arr = np.array([1, 5, 8, 12, 15])

filtered_array = arr[arr % 3 == 0]

print("Filtered array:")
print(filtered_array)


Filtered array:
[12 15]


70. Filter elements which are ≥ 20 and <= 40 from a given NumPy array.


In [32]:

arr = np.array([10, 20, 30, 40, 50])

filtered_array = arr[(arr >= 20) & (arr <= 40)]

print("Filtered array:")
print(filtered_array)


Filtered array:
[20 30 40]


71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.

In [35]:
arr = np.array([1, 2, 3,5])

byte_order = arr.dtype.byteorder


print("Byte order:", byte_order)


Byte order: =


72. For the given NumPy array, perform byte swapping in place using `byteswap()`


In [37]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

print(arr)
arr.byteswap(True)

print("Modified array after byte swapping:")
print(arr)


[1 2 3]
Modified array after byte swapping:
[16777216 33554432 50331648]


73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.

In [38]:
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)

swapped_arr = arr.newbyteorder()

print("Original array:")
print(arr)
print("\nSwapped array:")
print(swapped_arr)


Original array:
[1 2 3]

Swapped array:
[16777216 33554432 50331648]


74. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder().

In [39]:
import numpy as np
import sys

arr = np.array([1, 2, 3], dtype=np.int32)

swapped_arr = arr.newbyteorder(sys.byteorder)
print("Original array:")
print(arr)
print("\nSwapped array:")
print(swapped_arr)


Original array:
[1 2 3]

Swapped array:
[1 2 3]


75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder.

In [40]:
arr = np.array([1, 2, 3], dtype=np.int32)

byte_order = arr.dtype.byteorder

swapping_necessary = (byte_order != '=')

if swapping_necessary:
    print("Byte swapping is necessary for the current system.")
else:
    print("Byte swapping is not necessary for the current system.")


Byte swapping is not necessary for the current system.


76. Create a NumPy array `arrl with values from 1 to 10. Create a copy of `arrl` named `copy_arr` and modify an element in `copy_arr. Check if modifying `copy_arr` affects`arrl`.


In [41]:
arr1 = np.arange(1, 11)

copy_arr = arr1.copy()

copy_arr[0] = 100

# Check if modifying copy_arr affects arr1
print("Original array (arr1):", arr1)
print("Copied array (copy_arr):", copy_arr)


Original array (arr1): [ 1  2  3  4  5  6  7  8  9 10]
Copied array (copy_arr): [100   2   3   4   5   6   7   8   9  10]


77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice' from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.


In [43]:

matrix = np.random.randint(1, 10, size=(3, 3))
print("Original matrix:")
print(matrix)

view_slice = matrix[:2, :2]

view_slice[0, 0] = 100

print("Original matrix:")
print(matrix)
print("\nModified view_slice:")
print(view_slice)


Original matrix:
[[4 4 4]
 [7 3 5]
 [8 6 3]]
Original matrix:
[[100   4   4]
 [  7   3   5]
 [  8   6   3]]

Modified view_slice:
[[100   4]
 [  7   3]]


78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b`from `array_a`and broadcast the addition of 5 to view_b. Check if it alters the original`array_a`.


In [44]:
array_a = np.arange(1, 13).reshape(4, 3)

view_b = array_a[:2, :2]

view_b += 5

print("Original array_a:")
print(array_a)
print("\nModified view_b:")
print(view_b)


Original array_a:
[[ 6  7  3]
 [ 9 10  6]
 [ 7  8  9]
 [10 11 12]]

Modified view_b:
[[ 6  7]
 [ 9 10]]


79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view of shape (4, 2) from orig_array. Modify an element in `reshaped_view and check if it reflects changes in the original orig_array`.


In [45]:
orig_array = np.arange(1, 9).reshape(2, 4)
reshaped_view = orig_array.reshape(4, 2)

reshaped_view[0, 0] = 100

print("Original orig_array:")
print(orig_array)
print("\nModified reshaped_view:")
print(reshaped_view)


Original orig_array:
[[100   2   3   4]
 [  5   6   7   8]]

Modified reshaped_view:
[[100   2]
 [  3   4]
 [  5   6]
 [  7   8]]


80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy and verify if it affects the original `data`.


In [47]:
data = np.random.randint(1, 10, size=(3, 4))

data_copy = data[data > 5].copy()

data_copy[0] = 100

print("Original data:")
print(data)
print("\nModified data_copy:")
print(data_copy)


Original data:
[[4 5 3 9]
 [9 6 4 7]
 [4 1 5 6]]

Modified data_copy:
[100   9   6   7   6]


81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.


In [48]:

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

addition_result = A + B
subtraction_result = A - B

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nAddition Result:")
print(addition_result)
print("\nSubtraction Result:")
print(subtraction_result)


Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Addition Result:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Subtraction Result:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.


In [49]:

C = np.array([[1, 2],
              [3, 4],
              [5, 6]])

D = np.array([[7, 8, 9, 10],
              [11, 12, 13, 14]])

multiplication_result = np.dot(C, D)

print("Matrix C:")
print(C)
print("\nMatrix D:")
print(D)
print("\nMatrix Multiplication Result:")
print(multiplication_result)


Matrix C:
[[1 2]
 [3 4]
 [5 6]]

Matrix D:
[[ 7  8  9 10]
 [11 12 13 14]]

Matrix Multiplication Result:
[[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


83. Create a matrix `E` and find its transpose.


In [50]:
E = np.array([[1, 2, 3],
              [4, 5, 6]])

transpose_E = np.transpose(E)
print("Matrix E:")
print(E)
print("\nTranspose of E:")
print(transpose_E)


Matrix E:
[[1 2 3]
 [4 5 6]]

Transpose of E:
[[1 4]
 [2 5]
 [3 6]]


84. Generate a square matrix `F` and compute its determinant.


In [52]:

F = np.array([[1, 2, 3],
              [4, 577, 6],
              [7, 8, 9]])

determinant_F = np.linalg.det(F)

print("Determinant of matrix F:", determinant_F)


Determinant of matrix F: -6864.000000000008


85. Create a square matrix `G` and find its inverse.

In [53]:

G = np.array([[1, 2],
              [3, 4]])

inverse_G = np.linalg.inv(G)

print("Matrix G:")
print(G)
print("\nInverse of G:")
print(inverse_G)


Matrix G:
[[1 2]
 [3 4]]

Inverse of G:
[[-2.   1. ]
 [ 1.5 -0.5]]
